
par(mfrow=c(4,2))

pdf('panelmaps.pdf',height=48,width=32)
map('state',main='point size = max depth')
points(LAT_DD.y~LON_DD.y,data=nla,pch=21,bg='red',col='black',cex=scale(sqrt(nla$DEPTHMAX)))
plotizes<-scale(log(nla$TURB))
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = max depth')

pdf('depthbytype.pdf')
map('state',main='point size = max depth')
cols<-ifelse(nla$LAKE_ORIGIN.x=='NATURAL','green','red')
points(LAT_DD.y~LON_DD.y,data=nla,pch=21,bg=cols,col='black',cex=scale(log(nla$DEPTHMAX)))
plotizes<-scale(log(nla$DEPTHMAX))
nlaps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title(main='point size = log(max depth)',sub='green = Natural Lakes, red = Manmade')
dev.off()


map('state',main='point size = log conductivity')
points(LAT_DD.y~LON_DD.y,data=nla,pch=21,bg='orange',col='black',cex=scale(log(nla$COND)))
plotizes<-scale(log(nla$TURB))
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = conductivity')

map('state')
points(LAT_DD.y~LON_DD.y,data=nla,pch=21,bg='brown',col='black',cex=scale(log(nla$DOC)))
plotizes<-scale(log(nla$TURB))
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = DOC')

map('state')
points(LAT_DD.y~LON_DD.y,data=nla,pch=21,bg='grey',col='black',cex=scale(log(nla$TURB)))
plotizes<-scale(log(nla$TURB))
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = TURB')

pdf('totalP.pdf')
map('state')
points(LAT_DD.y~LON_DD.y,data=nla,pch=21,bg='green',col='black',cex=scale(log(nla$PTL)))
plotizes<-scale(log(nla$PTL))
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = total P')
dev.off()

pdf('totalN.pdf')
map('state')
points(LAT_DD.y~LON_DD.y,data=nla,pch=21,bg='red',col='black',cex=scale(log(nla$NTL)))
plotizes<-scale(log(nla$NTL)
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = total N')
dev.off()

map('state')
points(LAT_DD.y~LON_DD.y,data=nla2,pch=21,bg='blue',col='black',cex=scale(log(nla2$SECMEAN)))
plotizes<-scale(log(nla$TURB))
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = secchi depth')

map('state')
points(LAT_DD.y~LON_DD.y,data=nla2,pch=21,bg='yellow',col='black',cex=scale(log(nla2$CL)))
plotizes<-scale(log(nla$TURB))
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = chloride')

map('state')
points(LAT_DD.y~LON_DD.y,data=nla2,pch=21,bg='red',col='black',cex=scale(log(nla2$CA)))
plotizes<-scale(log(nla$TURB))
ps.range<-quantile(plotizes,c(.66,.75,.95))
legend(-118,30,bty='n',legend=c('low','med','high')
,pch=21,pt.cex=ps.range)
title('point size = calcium')
dev.off()
